// MRa data-platform mock data — realistic, present-day.

const MATERIALS = [
  {
    id: "lithium",
    name: "Lithium",
    symbol: "Li",
    category: "Battery metal",
    iraCritical: true,
    euCrma: true,
    criticality: 92,
    overallRisk: 78,
    pillars: { material: 71, geo: 88, regulatory: 82, operational: 64, financial: 70 },
    countries: [
      { code: "AU", flag: "🇦🇺", share: 47 },
      { code: "CL", flag: "🇨🇱", share: 24 },
      { code: "CN", flag: "🇨🇳", share: 18 },
      { code: "AR", flag: "🇦🇷", share: 6 },
    ],
    chemistries: ["NMC", "NCA", "LFP", "LCO"],
    hsMappings: 14,
    mismatches: 0,
    trend: "rising",
    asOf: "Apr 21, 2026",
  },
  {
    id: "cobalt",
    name: "Cobalt",
    symbol: "Co",
    category: "Battery metal",
    iraCritical: true,
    euCrma: true,
    criticality: 96,
    overallRisk: 84,
    pillars: { material: 92, geo: 88, regulatory: 71, operational: 86, financial: 64 },
    countries: [
      { code: "CD", flag: "🇨🇩", share: 74 },
      { code: "ID", flag: "🇮🇩", share: 8 },
      { code: "RU", flag: "🇷🇺", share: 5 },
      { code: "AU", flag: "🇦🇺", share: 4 },
    ],
    chemistries: ["NMC", "NCA", "LCO"],
    hsMappings: 11,
    mismatches: 2,
    trend: "stable",
    asOf: "Apr 21, 2026",
  },
  {
    id: "graphite",
    name: "Graphite (natural)",
    symbol: "C",
    category: "Anode material",
    iraCritical: true,
    euCrma: true,
    criticality: 89,
    overallRisk: 81,
    pillars: { material: 83, geo: 91, regulatory: 87, operational: 58, financial: 60 },
    countries: [
      { code: "CN", flag: "🇨🇳", share: 79 },
      { code: "MZ", flag: "🇲🇿", share: 6 },
      { code: "MG", flag: "🇲🇬", share: 5 },
      { code: "BR", flag: "🇧🇷", share: 4 },
    ],
    chemistries: ["NMC", "NCA", "LFP"],
    hsMappings: 9,
    mismatches: 1,
    trend: "rising",
    asOf: "Apr 21, 2026",
  },
  {
    id: "nickel",
    name: "Nickel",
    symbol: "Ni",
    category: "Battery metal",
    iraCritical: true,
    euCrma: true,
    criticality: 86,
    overallRisk: 64,
    pillars: { material: 58, geo: 72, regulatory: 65, operational: 70, financial: 55 },
    countries: [
      { code: "ID", flag: "🇮🇩", share: 49 },
      { code: "PH", flag: "🇵🇭", share: 12 },
      { code: "RU", flag: "🇷🇺", share: 9 },
      { code: "AU", flag: "🇦🇺", share: 6 },
    ],
    chemistries: ["NMC", "NCA"],
    hsMappings: 12,
    mismatches: 0,
    trend: "stable",
    asOf: "Apr 21, 2026",
  },
  {
    id: "manganese",
    name: "Manganese",
    symbol: "Mn",
    category: "Battery metal",
    iraCritical: true,
    euCrma: false,
    criticality: 71,
    overallRisk: 52,
    pillars: { material: 62, geo: 49, regulatory: 41, operational: 54, financial: 50 },
    countries: [
      { code: "ZA", flag: "🇿🇦", share: 36 },
      { code: "GA", flag: "🇬🇦", share: 22 },
      { code: "AU", flag: "🇦🇺", share: 16 },
      { code: "CN", flag: "🇨🇳", share: 9 },
    ],
    chemistries: ["NMC", "LMO"],
    hsMappings: 8,
    mismatches: 0,
    trend: "stable",
    asOf: "Apr 19, 2026",
  },
  {
    id: "ree",
    name: "Rare earth elements",
    symbol: "REE",
    category: "Component / magnet",
    iraCritical: true,
    euCrma: true,
    criticality: 94,
    overallRisk: 86,
    pillars: { material: 95, geo: 93, regulatory: 78, operational: 68, financial: 72 },
    countries: [
      { code: "CN", flag: "🇨🇳", share: 68 },
      { code: "MM", flag: "🇲🇲", share: 12 },
      { code: "US", flag: "🇺🇸", share: 9 },
      { code: "AU", flag: "🇦🇺", share: 5 },
    ],
    chemistries: ["NMC", "NCA", "Solid-state"],
    hsMappings: 18,
    mismatches: 3,
    trend: "rising",
    asOf: "Apr 17, 2026",
  },
  {
    id: "copper",
    name: "Copper",
    symbol: "Cu",
    category: "Conductor",
    iraCritical: false,
    euCrma: true,
    criticality: 64,
    overallRisk: 41,
    pillars: { material: 38, geo: 42, regulatory: 28, operational: 47, financial: 50 },
    countries: [
      { code: "CL", flag: "🇨🇱", share: 28 },
      { code: "PE", flag: "🇵🇪", share: 12 },
      { code: "CN", flag: "🇨🇳", share: 9 },
      { code: "CD", flag: "🇨🇩", share: 8 },
    ],
    chemistries: ["NMC", "NCA", "LFP", "LCO", "LMO"],
    hsMappings: 7,
    mismatches: 0,
    trend: "declining",
    asOf: "Apr 21, 2026",
  },
  {
    id: "phosphate",
    name: "Phosphate (LFP grade)",
    symbol: "P",
    category: "Cathode precursor",
    iraCritical: false,
    euCrma: true,
    criticality: 58,
    overallRisk: 47,
    pillars: { material: 54, geo: 61, regulatory: 38, operational: 42, financial: 38 },
    countries: [
      { code: "CN", flag: "🇨🇳", share: 41 },
      { code: "MA", flag: "🇲🇦", share: 18 },
      { code: "US", flag: "🇺🇸", share: 11 },
      { code: "RU", flag: "🇷🇺", share: 8 },
    ],
    chemistries: ["LFP"],
    hsMappings: 5,
    mismatches: 0,
    trend: "rising",
    asOf: "Apr 17, 2026",
  },
];

const CHEMISTRIES = [
  { id: "nmc811", name: "NMC 811", family: "NMC", risk: 74, cells: 1842, oems: 23, materials: ["Li","Ni","Co","Mn","C"], mix: "Ni 80 · Mn 10 · Co 10", energy: "270 Wh/kg" },
  { id: "nmc622", name: "NMC 622", family: "NMC", risk: 68, cells: 1271, oems: 19, materials: ["Li","Ni","Co","Mn","C"], mix: "Ni 60 · Mn 20 · Co 20", energy: "240 Wh/kg" },
  { id: "lfp",   name: "LFP",     family: "LFP", risk: 51, cells: 2410, oems: 31, materials: ["Li","Fe","P","C"],     mix: "LiFePO₄",          energy: "170 Wh/kg" },
  { id: "nca",   name: "NCA",     family: "NCA", risk: 78, cells:  612, oems:  7, materials: ["Li","Ni","Co","Al","C"], mix: "Ni 80 · Co 15 · Al 5", energy: "260 Wh/kg" },
  { id: "lmfp",  name: "LMFP",    family: "LFP", risk: 55, cells:  198, oems:  9, materials: ["Li","Mn","Fe","P","C"],  mix: "LiMnFePO₄",        energy: "210 Wh/kg" },
  { id: "lto",   name: "LTO",     family: "Other", risk: 44, cells:  82, oems:  4, materials: ["Li","Ti"],              mix: "Li₄Ti₅O₁₂",         energy: "80 Wh/kg" },
  { id: "ss",    name: "Solid-state (sulfide)", family: "Solid-state", risk: 82, cells: 14, oems: 6, materials: ["Li","REE","S","C"], mix: "Li-S electrolyte", energy: "400 Wh/kg" },
  { id: "nasi",  name: "Na-ion",  family: "Sodium", risk: 38, cells: 47, oems: 5, materials: ["Na","Mn","Fe","C"],   mix: "Prussian-blue cathode", energy: "150 Wh/kg" },
];

const RECENT_NOTES = [
  { id: 1, who: "M. Reyes", entity: "Cobalt — HS 2822.00", when: "2h ago", type: "data_error", text: "HS prefix 2822.00 is mapped to Cobalt but customs description references nickel oxide. Suspect — needs review." },
  { id: 2, who: "K. Tanaka", entity: "Graphite (natural) — CN", when: "Yesterday", type: "outdated", text: "CN export licensing tightened Apr 17; concentration score may understate near-term risk." },
  { id: 3, who: "P. Adeyemi", entity: "REE — MM", when: "2d ago", type: "missing_data", text: "Myanmar share rising per USGS preliminary; we still carry the 2024 figure (8%). Update once finalised." },
  { id: 4, who: "J. Holm", entity: "Lithium — AR", when: "3d ago", type: "data_error", text: "Argentina production figures appear duplicated across two facility records — verify before next score run." },
];

window.MRA_DATA = { MATERIALS, CHEMISTRIES, RECENT_NOTES };
