/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Ingestion */
        post: operations["trigger_ingestion_api_v1_sources__source_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Runs */
        get: operations["list_ingestion_runs_api_v1_ingestion_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Risk Events */
        get: operations["list_risk_events_api_v1_risk_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regulations */
        get: operations["list_regulations_api_v1_regulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Paginated, filterable company list with the latest overall score joined in.
         */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/exposures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Exposures */
        get: operations["get_company_exposures_api_v1_companies__company_id__exposures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Relationships */
        get: operations["get_company_relationships_api_v1_companies__company_id__relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/regulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Regulations */
        get: operations["get_company_regulations_api_v1_companies__company_id__regulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Events */
        get: operations["get_company_events_api_v1_companies__company_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Facilities */
        get: operations["get_company_facilities_api_v1_companies__company_id__facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/vehicle-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Vehicle Models */
        get: operations["get_company_vehicle_models_api_v1_companies__company_id__vehicle_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Notes */
        get: operations["get_company_notes_api_v1_companies__company_id__notes_get"];
        put?: never;
        /** Create Company Note */
        post: operations["create_company_note_api_v1_companies__company_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Rescore */
        post: operations["trigger_rescore_api_v1_companies__company_id__rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Overview */
        get: operations["dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trade Flows */
        get: operations["list_trade_flows_api_v1_trade_flows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalystNoteCreate
         * @description Body for ``POST /companies/{id}/notes``. ``entity_type`` defaults to
         *     ``company`` since the Phase 1 dialog always targets companies.
         */
        AnalystNoteCreate: {
            /**
             * Note Type
             * @enum {string}
             */
            note_type: "data_error" | "missing_data" | "outdated" | "other";
            /** Note Text */
            note_text: string;
            /**
             * Entity Type
             * @default company
             * @constant
             */
            entity_type: "company";
        };
        /** AnalystNoteRead */
        AnalystNoteRead: {
            /** Id */
            id: number;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /** Note Type */
            note_type: string;
            /** Note Text */
            note_text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CompanyAliasRead */
        CompanyAliasRead: {
            /** Id */
            id: number;
            /** Alias */
            alias: string;
            /** Alias Type */
            alias_type: string;
        };
        /** CompanyDetail */
        CompanyDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Legal Name */
            legal_name?: string | null;
            /** Supply Chain Stage */
            supply_chain_stage?: string | null;
            /** Headquarters Country */
            headquarters_country?: string | null;
            /** Headquarters Region */
            headquarters_region?: string | null;
            /** Public Ticker */
            public_ticker?: string | null;
            /** Is Public */
            is_public: boolean;
            /** Duns Number */
            duns_number?: string | null;
            /** Lei */
            lei?: string | null;
            /** Data Confidence */
            data_confidence?: number | null;
            /** Data Source */
            data_source?: string | null;
            /** Notes */
            notes?: string | null;
            /** Parent Company Id */
            parent_company_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Aliases */
            aliases?: components["schemas"]["CompanyAliasRead"][];
            parent?: components["schemas"]["CompanySummary"] | null;
        };
        /** CompanyEventRead */
        CompanyEventRead: {
            /** Id */
            id: number;
            /** Event Type */
            event_type: string;
            /** Event Date */
            event_date?: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Severity Score */
            severity_score?: number | null;
            /** Confidence Score */
            confidence_score?: number | null;
            /** Relevance Score */
            relevance_score?: number | null;
            /** Match Reason */
            match_reason?: string | null;
        };
        /**
         * CompanyListItem
         * @description Row shape returned by ``GET /companies``. Includes the latest overall
         *     risk score (if any) so the list can render a band badge per row.
         */
        CompanyListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Legal Name */
            legal_name?: string | null;
            /** Supply Chain Stage */
            supply_chain_stage?: string | null;
            /** Headquarters Country */
            headquarters_country?: string | null;
            /** Is Public */
            is_public: boolean;
            /** Data Confidence */
            data_confidence?: number | null;
            /** Parent Company Id */
            parent_company_id?: string | null;
            /** Parent Company Name */
            parent_company_name?: string | null;
            /** Latest Overall Score */
            latest_overall_score?: number | null;
            /** Latest Risk Band */
            latest_risk_band?: string | null;
            /** Latest Score As Of Date */
            latest_score_as_of_date?: string | null;
        };
        /**
         * CompanySummary
         * @description Used for the ``parent`` field on the detail view and other lightweight refs.
         */
        CompanySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Supply Chain Stage */
            supply_chain_stage?: string | null;
        };
        /** ConfidenceBucket */
        ConfidenceBucket: {
            /** Bucket */
            bucket: string;
            /** Count */
            count: number;
        };
        /** DashboardOverview */
        DashboardOverview: {
            /** Company Count Total */
            company_count_total: number;
            /** Company Count By Stage */
            company_count_by_stage?: components["schemas"]["StageCount"][];
            /** Confidence Distribution */
            confidence_distribution?: components["schemas"]["ConfidenceBucket"][];
            /** Companies With Score */
            companies_with_score: number;
            /** Recent Notes Count 7D */
            recent_notes_count_7d: number;
        };
        /** ExposureRead */
        ExposureRead: {
            /** Id */
            id: number;
            /** Material Id */
            material_id: number;
            /** Material Name */
            material_name: string;
            /** Supply Chain Stage */
            supply_chain_stage: string;
            /** Exposure Score */
            exposure_score: number;
            /** Source Geography */
            source_geography?: string | null;
            /** Data Confidence */
            data_confidence?: number | null;
            /** Rationale */
            rationale?: string | null;
            /** As Of Date */
            as_of_date?: string | null;
        };
        /** FacilityRead */
        FacilityRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Facility Type */
            facility_type: string;
            /** Country */
            country: string;
            /** Region */
            region?: string | null;
            /** City */
            city?: string | null;
            /** Status */
            status: string;
            /** Capacity Notes */
            capacity_notes?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Service
             * @default battery-data-intelligence-engine
             */
            service: string;
        };
        /** IngestionRunRead */
        IngestionRunRead: {
            /** Id */
            id: number;
            /** Source Id */
            source_id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Parameters Json */
            parameters_json?: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
            /** Stats Json */
            stats_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * IngestionTriggerRequest
         * @description Optional parameters passed to a source-specific ingestion run.
         */
        IngestionTriggerRequest: {
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /** PaginatedResponse[CompanyListItem] */
        PaginatedResponse_CompanyListItem_: {
            /** Data */
            data: components["schemas"]["CompanyListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** RegulationExposureRead */
        RegulationExposureRead: {
            /** Id */
            id: number;
            /** Regulation Id */
            regulation_id: number;
            /** Regulation Title */
            regulation_title?: string | null;
            /** Regulation Key */
            regulation_key: string;
            /** Policy Theme */
            policy_theme?: string | null;
            /** Effective Date */
            effective_date?: string | null;
            /** Compliance Status */
            compliance_status: string;
            /** Exposure Reason */
            exposure_reason?: string | null;
            /** Assessed At */
            assessed_at?: string | null;
        };
        /** RegulationRead */
        RegulationRead: {
            /** Id */
            id: number;
            /** Source Document Id */
            source_document_id: number;
            /** Regulation Key */
            regulation_key: string;
            /** Title */
            title?: string | null;
            /** Issuing Body */
            issuing_body?: string | null;
            /** Geography */
            geography?: string | null;
            /** Policy Theme */
            policy_theme?: string | null;
            /** Status */
            status?: string | null;
            /** Publication Date */
            publication_date?: string | null;
            /** Effective Date */
            effective_date?: string | null;
            /** Summary */
            summary?: string | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RelationshipCounterparty */
        RelationshipCounterparty: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Supply Chain Stage */
            supply_chain_stage?: string | null;
        };
        /** RelationshipRead */
        RelationshipRead: {
            /** Id */
            id: number;
            /** Relationship Type */
            relationship_type: string;
            /** Material Id */
            material_id?: number | null;
            /** Material Name */
            material_name?: string | null;
            /** Data Confidence */
            data_confidence?: number | null;
            /** Volume Share Pct */
            volume_share_pct?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            counterparty: components["schemas"]["RelationshipCounterparty"];
        };
        /** RelationshipsResponse */
        RelationshipsResponse: {
            /** As Buyer */
            as_buyer?: components["schemas"]["RelationshipRead"][];
            /** As Supplier */
            as_supplier?: components["schemas"]["RelationshipRead"][];
        };
        /** RiskEventRead */
        RiskEventRead: {
            /** Id */
            id: number;
            /** Source Document Id */
            source_document_id?: number | null;
            /** Event Type */
            event_type: string;
            /** Event Date */
            event_date?: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Severity Score */
            severity_score?: number | null;
            /** Confidence Score */
            confidence_score?: number | null;
            /** Risk Categories Json */
            risk_categories_json?: unknown[] | {
                [key: string]: unknown;
            } | null;
            /** Geography Json */
            geography_json?: unknown[] | {
                [key: string]: unknown;
            } | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SourceRead */
        SourceRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Source Type */
            source_type: string;
            /** Phase */
            phase: string;
            /** Is Active */
            is_active: boolean;
            /** Config Json */
            config_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StageCount */
        StageCount: {
            /** Stage */
            stage: string;
            /** Count */
            count: number;
        };
        /** TradeFlowRead */
        TradeFlowRead: {
            /** Id */
            id: number;
            /** Source Document Id */
            source_document_id: number;
            /** Period */
            period: string;
            /** Reporter Country */
            reporter_country: string;
            /** Partner Country */
            partner_country: string;
            /** Hs Code */
            hs_code?: string | null;
            /** Hs Description */
            hs_description?: string | null;
            /** Material Id */
            material_id?: number | null;
            /** Import Export Flag */
            import_export_flag: string;
            /** Quantity */
            quantity?: number | null;
            /** Quantity Unit */
            quantity_unit?: string | null;
            /** Trade Value Usd */
            trade_value_usd?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VehicleModelChemistryRead */
        VehicleModelChemistryRead: {
            /** Id */
            id: number;
            /** Battery Chemistry Id */
            battery_chemistry_id: number;
            /** Chemistry Slug */
            chemistry_slug: string;
            /** Share Pct */
            share_pct: number;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** VehicleModelRead */
        VehicleModelRead: {
            /** Id */
            id: number;
            /** Model Name */
            model_name: string;
            /** Model Year Start */
            model_year_start?: number | null;
            /** Model Year End */
            model_year_end?: number | null;
            /** Production Volume Units */
            production_volume_units?: number | null;
            /** Production Volume Year */
            production_volume_year?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Data Source */
            data_source?: string | null;
            /** Chemistries */
            chemistries?: components["schemas"]["VehicleModelChemistryRead"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"][];
                };
            };
        };
    };
    trigger_ingestion_api_v1_sources__source_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IngestionTriggerRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestion_runs_api_v1_ingestion_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_risk_events_api_v1_risk_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regulations_api_v1_regulations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string | null;
                stage?: string | null;
                country?: string | null;
                parent_id?: string | null;
                min_confidence?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_CompanyListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_exposures_api_v1_companies__company_id__exposures_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_relationships_api_v1_companies__company_id__relationships_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_regulations_api_v1_companies__company_id__regulations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulationExposureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_events_api_v1_companies__company_id__events_get: {
        parameters: {
            query?: {
                limit?: number;
                event_type?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_facilities_api_v1_companies__company_id__facilities_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_vehicle_models_api_v1_companies__company_id__vehicle_models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleModelRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_notes_api_v1_companies__company_id__notes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalystNoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_note_api_v1_companies__company_id__notes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalystNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalystNoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_rescore_api_v1_companies__company_id__rescore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trade_flows_api_v1_trade_flows_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeFlowRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
